# This workflow will upload a Python Package to PyPI when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CI Pipeline - C214

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar Pipenv e dependências
        run: |
          pip install pipenv
          pipenv install --dev

      - name: Executar testes
        run: |
          pipenv run pytest --junitxml=report.xml

      - name: Salvar relatório de testes
        uses: actions/upload-artifact@v3
        with:
          name: relatorio-testes
          path: report.xml
          
  build:
    runs-on: ubuntu-latest
    needs: tests  
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependências e PyInstaller
        run: |
          pip install pipenv
          pipenv install
          pipenv install pyinstaller

      - name: Build do executável
        run: |
          pipenv run pyinstaller --onefile main.py

      - name: Salvar artefato (executável)
        uses: actions/upload-artifact@v3
        with:
          name: executavel
          path: dist/main
